name: 'Publish'

on:
  push:
    branches: ['master']

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Automated version bump'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'

      - name: 'Create GitHub release'
        uses: 'danielnakamashi/simple-github-release@v1'
        with:
          token: ${{secrets.ACTION_RW}}
