name: 'Version bump'

on:
  push:
    branches: ['master']

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Automated version bump'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'
